const fs = require('fs'), vm = require('vm'), assert = require('assert');
const element = {querySelector: () => ({innerHTML: ''}), querySelectorAll: () => [1,2]};
let reloads = [], config;
const table = {ajax:{reload: (callback,reset) => reloads.push(reset)}};
const jquery = () => ({DataTable: opts => {config=opts; return table;}});
jquery.fn = {DataTable:true};
const ctx = vm.createContext({URL, AbortController, console, window:{location:{href:'http://localhost/leaves.php'},jQuery:jquery}, jQuery:jquery, document:{getElementById:()=>element}});
vm.runInContext(fs.readFileSync('assets/js/paged_tables.js','utf8'),ctx);
ctx.options = {tableId:'list',url:'api/list.php?status=pending',renderRow:()=>''};
vm.runInContext('loadServerTable(options)',ctx);
vm.runInContext('loadServerTable({...options})',ctx);
assert.equal(reloads.pop(),false,'Refreshing after an action must preserve the page and search');
vm.runInContext("loadServerTable({...options,url:'api/list.php?status=approved'})",ctx);
assert.equal(reloads.pop(),true,'Changing filters must reset page');
vm.runInContext("loadServerTable({...options,url:()=> 'api/list.php?status=approved'})",ctx);
assert.equal(reloads.pop(),false,'Function URLs must compare their actual filters');
vm.runInContext("loadServerTable({...options,resetPaging:true})",ctx);
assert.equal(reloads.pop(),true,'Explicit reset must reset page');
console.log('PASS table refresh retains location and detects changed filters');